# name: morning
# on:
#   schedule:
#   - cron:  '0 0 * * *'
#   workflow_dispatch:

# jobs:
#   send_message:
#     runs-on: ubuntu-latest
#     name: send morning to your girlfriend

#     steps:
#     - name: checkout
#       uses: actions/checkout@v3
#       with:
#         ref: master

#     - name: sender
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.x'
#         architecture: 'x64'
#     # - run: pip install -r ./requirements.txt && python ./main.py
#     - run:
#       python -m pip install --upgrade pip
#       pip3 install -r requirements.txt 
#       python main.py
      

#     env:
#       APP_ID: ${{ secrets.APP_ID }}
#       APP_SECRET: ${{ secrets.APP_SECRET }}
#       TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
#       USER_ID: ${{ secrets.USER_ID }}
#       START_DATE: ${{ secrets.START_DATE }}
#       BIRTHDAY: ${{ secrets.BIRTHDAY }}
#       CITY: ${{ secrets.CITY }}

name: weixin
on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间4点0分，北京时间需要+8小时，代表北京时间中午12点运行
    - cron: '0 4 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Set timezone
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: weixin
        run: |
          python3 main.py

      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        USER_ID: ${{ secrets.USER_ID }}
        START_DATE: ${{ secrets.START_DATE }}
        BIRTHDAY: ${{ secrets.BIRTHDAY }}
        CITY: ${{ secrets.CITY }}